services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      VITE_ORIGINAL_URL: https://landlapi.ddnsking.com/api/
      VITE_MAPBOX_URL: pk.eyJ1IjoiaGlldXNlcnZpY2VzIiwiYSI6ImNtMXA1bmh6MjAwbjUycXNicm1hdmJqNnkifQ.pULi1W0EzO_pMU2fHv0bVQ
      VITE_GOONG_API_KEY: ifBTELKALjBVkD41bM2bh5Kly5wXr0rI5M3ideAM
      VITE_MAP_STYLE: mapbox://styles/hieuservices/cm0y0ezhf012101pmg9f01txf
      VITE_GOONG_URL_SEARCH: https://rsapi.goong.io/Place/AutoComplete
      VITE_GOONG_URL_DIRECTION: https://rsapi.goong.io/Direction
      VITE_GOONG_URL_GEOCODING: https://rsapi.goong.io/geocode
      VITE_GOONG_URL_PLACE_DETAIL: https://rsapi.goong.io/Place/Detail
      VITE_AUTH0_CALLBACK_URL: https://leopardlorry.com
      VITE_AUTH0_DOMAIN: dev-1z7owtnvo1o7zl2m.us.auth0.com
      VITE_AUTH0_CLIENT_ID: 8jcCFw1kgB3UTbrKTJP0IvbixEQ72n6m
      VITE_AUTH0_AUDIENCE: L&Lservices
    ports:
      - 5176:5173
